version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt || true

  pre_build:
    commands:
      - echo "Zipping Lambda files..."
      - chmod +x scripts/zip_lambdas.sh
      - ./scripts/zip_lambdas.sh

  build:
    commands:
      - cd infra
      - terraform init
      - terraform fmt -check
      - terraform validate
      - terraform plan -input=false
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Running tests..."
      - pytest tests || true

artifacts:
  files:
    - '**/*'
